<?php

namespace Tyras\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublishedNews($resType = 'result')
    {
        $qb = $this->createQueryBuilder('n');

        $qb->where('n.enabled = true')
            ->andWhere('n.date <= CURRENT_TIMESTAMP()')
            ->orderBy('n.date', 'DESC');


        if ($resType == 'result'){
            $qb->setMaxResults(5);
            return $qb->getQuery()->getResult();
        }
        else
            return $qb->getQuery();
    }
}
