<?php

namespace Tyras\NewsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Query\Builder;

/**
 * NewsRepositoryODM
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class NewsRepositoryODM extends DocumentRepository
{
    public function findPublishedNews($resType = 'result')
    {
        $qb = $this->createQueryBuilder('News');

        $qb->field('enabled')->equals(true)
            ->field('date')->lte(new \Datetime())
            ->sort('date', 'desc');


        if ($resType == 'result'){
            $qb->limit(5);
            return $qb->getQuery()->getResult();
        }
        else
            return $qb->getQuery();
    }
}
