# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    Tyras\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_TICKET_ADMIN]
    ROLE_MODERATOR: [ROLE_USER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:      ^/
      anonymous:    ~
      provider:     main
      ajax_form_login:
        login_path: /
        check_path: fos_user_security_check
        default_target_path:  fos_user_profile_show
        csrf_token_generator: security.csrf.token_manager
      logout:
        path:       fos_user_security_logout
        target:     /
      remember_me:
        secret:     "%secret%"
      oauth:
        resource_owners:
          facebook:           "/connect/check-facebook"
          google:             "/connect/check-google"
          twitter:            "/connect/check-twitter"
        login_path:        /connect
        failure_path:      /connect
        oauth_user_provider:
          service: my_user_provider

      anonymous:    ~


  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_ADMIN }
    - { path: ^/ticket, role: ROLE_USER }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
