<?php

namespace Tyras\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepositoryODB
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepositoryODB extends DocumentRepository
{
}
