tyras_core_homepage:
  path:     /
  defaults: { _controller: TyrasCoreBundle:Core:index }

tyras_core_gallery:
  path:     /gallery
  defaults: { _controller: TyrasCoreBundle:Core:gallery }

tyras_core_upload_gallery:
  path:     /upload
  defaults: { _controller: TyrasCoreBundle:Core:upload }
